### PR TITLE
FIX: homer-api RPMs build with MySQL/PgSQL scripts/SQLs

### PR DESCRIPTION
**Pull request by kvishnivetsky**
Modified subdirectory structure for **sql** and **scripts** dirs.
Renamed/moved some scripts for dir structure unification.
Updated **homer-api.spec** for new directory structure.
Update package structure in homer-api.spec, added new subpackages for MySQL and PgSQL scripts and SQL files.

### CODE REVIEW

**Comment by adubovikov** [comment]
Thank you!

**Comment by adubovikov** [comment]
@kvishnivetsky please next time do also changes in the installation scripts, because now it has been broken....

**Comment by kvishnivetsky** [comment]
Ok.

**Comment by adubovikov** [comment]
thank you

**Pull request merged**
