### PR TITLE
Rotation scripts: bugfixes and a new partition cleanup script

### PR DESCRIPTION
**Pull request by SipSeb**
There are a few bugfixes:
- generate correct partitions
- calculate correct start of day
- respect configuration file for stats tables

And there is a new script which can be run during the day to cleanup old partitions in current day's table.

### CODE REVIEW

**Comment by adubovikov** [comment]
why there is localtime vs gmtime ?

**Comment by SipSeb** [comment]
As you said on the phone, everything in Homer should happen in UTC. When running the current rotate script with partitioning set to 1 (hourly), partitions started at 23 o'clock on the previous day during daylight savings time, and the last hour would end up in the pmax partition. This is due to the fact that gmtime always returns a 0 for DST, which in return leads to mktime generating wrong timestamps.
I tried to make the commit messages as verbose as I could. :)

**Comment by adubovikov** [comment]
@SipSeb , thank you. Maybe better if we will keep it in "gmtime" and use timegm function ? We can also copy it directly to the rotation script.

https://metacpan.org/source/PEVANS/Time-timegm-0.01/lib/Time/timegm.pm

**Comment by SipSeb** [comment]
I found this lib, too, but since it isn't included in Debian and since the function is so short, I thought doing it with included methods is easier.
Isn't including the function in the script practically the same thing as defining an own function?

**Comment by adubovikov** [comment]
ok, at the end it does same job, but for styling it looks much better if we will use "utc function" always. Just my 5 cents. We can first do as you proposed and later we can change. Thank you again!

**Pull request merged**
