### PR TITLE
Work in progress isup queries

### PR DESCRIPTION
**Pull request by zecke**
Extend to allow isup to be queried using the same queries known from SIP. Map some SIP field names to ISUP.

### CODE REVIEW

**Comment by adubovikov** [comment]
And here ;-)

**Comment by zecke** [comment]
Hehe! that was quick. Thank you! Maybe Lorenzo has some feedback here. Not sure that the code duplication is the right thing and maybe i broke SIP (well it seemed to work but I don't have much experience with homer-ui)

**Comment by adubovikov** [comment]
no no, the direction is ok :-) isup will be like additional transaction type for this. As a first step - absolute brilliant :) thank you!

**Comment by lmangani** [comment]
Will do some deeper testing but looks fantastic, Holger - thanks!
Any chance we can create an initial model in HEPGen to mock some data?

**Pull request merged**
