### PR TITLE
Use configuration DB port when not overwritten by node

### PR DESCRIPTION
**Pull request by giavac**
I had to apply this patch when testing with a local node with non-standard mysql port.

### CODE REVIEW

**Comment by adubovikov** [comment]
@giavac can you please sign CLA ?

**Comment by giavac** [comment]
There must be a little glitch because I have signed it, but it's not shown in this PR. Looking.

**Comment by lmangani** [comment]
@giavac probably signed with a different email? 

https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by giavac** [comment]
Yes, let me do one thing: I'll close this PR and re-create with the commit not only associated with my github account but also the same email address as in the CLA.

**Pull request closed without merging**
