### PR TITLE
Fix passing the mysql password inside rotate.sh

### PR DESCRIPTION
**Pull request by giavac**

### CODE REVIEW

**Comment by adubovikov** [comment]
i think you wanna change it to: -p${MYSQL_PASSWORD} ?

**Comment by giavac** [comment]
Yes please. Sorry, I closed by mistake. Thanks.

**Comment by giavac** [comment]
Oh, I see my typo now...

**Comment by giavac** [comment]
OK, so I was such in a rush that created the pull request with a typo ('{$' instead of '${').
The only real issue was the missing space between '-p' and the password.
Thanks again for the fix.

**Pull request closed without merging**
