### PR TITLE
add option DB_TABLE_ROTATE to toggle naming of homer_data tables

### PR DESCRIPTION
**Pull request by boettner**
In case you'll let mysql or cron do the cleanup/rotate of sip_capture tables you need an option to not search in tables with date addition.

### CODE REVIEW

**Comment by adubovikov** [comment]
Hi, 
thank you for the patch, but whats a sense to use such scenario ? I mean the table's name without timestamp ?

**Comment by boettner** [comment]
We use this MySQL Partitioning feature you introduced us with Homer 3.5 :)

A major advantage is the ability of influencing the granularity. For example we store the REGISTERs in a table for only 6 hours. This is not possible with the a granularity of days. 

This is our register table:

CREATE TABLE `reg_capture` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
[...]
  `msg` varchar(1500) NOT NULL,
  PRIMARY KEY (`id`,`date`),
  KEY `ruri_user` (`ruri_user`),
[...]
  KEY `callid` (`callid`)
) ENGINE=InnoDB AUTO_INCREMENT=126668415408 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
/*!50100 PARTITION BY RANGE ( UNIX_TIMESTAMP(`date`))
(PARTITION p2016020213 VALUES LESS THAN (1454418000) ENGINE = InnoDB,
 PARTITION p2016020214 VALUES LESS THAN (1454421600) ENGINE = InnoDB,
 PARTITION p2016020215 VALUES LESS THAN (1454425200) ENGINE = InnoDB,
 PARTITION p2016020216 VALUES LESS THAN (1454428800) ENGINE = InnoDB,
 PARTITION p2016020217 VALUES LESS THAN (1454432400) ENGINE = InnoDB,
 PARTITION p2016020218 VALUES LESS THAN (1454436000) ENGINE = InnoDB,
 PARTITION pmax VALUES LESS THAN MAXVALUE ENGINE = InnoDB)

So the rotation is done in mysql and the table name doesn't change.

**Comment by boettner** [comment]
Is there something I can do to bring this upstream?

**Comment by adubovikov** [comment]
I am a bit skeptical for these patches, but lets discuss:

is it not easy to do same for timestamped tables ? in same way you can run your rotation script and just add to a table date timestamp: (current ts - 21600 seconds) and drop old partitions older than 6 hours ? 

again, thank you for your patches!

**Comment by adubovikov** [comment]
I think we can close it. Please re-open if anything.

**Comment by SipSeb** [comment]
@adubovikov Sorry for the late reply, but we stumbled upon this problem again when trying to use the current upstream version.

I think there are a couple of reasons why partitioning by table name is not optimal.
1. You have to know the partition naming strategy and interval in all components. So Kamailio and the Homer API have to know the correct table names. If we used single table names and just rotated in the background using MySQL partitioning, we would only need to know a single table name.
2. It is impossible to rotate tables more than once a day. Furthermore rotating different tables in different intervals is not supported. 
3. The sip_\* tables created by the new partitioning method are incompatible to the old Webhomer. (Ok, edge case...)

Can we discuss that again please? We really would like to go with upstream Homer, but we need the freedom to choose our rotation strategy. The patch provided in February won't work anymore but we would happily provide a new patch.

**Comment by adubovikov** [comment]
@SipSeb can you call me tomorrow afternoon ? we will discuss it and find a solution

**Comment by SipSeb** [comment]
Sure, will do.

**Pull request closed without merging**
