### PR TITLE
Isup schema proposal

### PR DESCRIPTION
**Pull request by zecke**
Okay, this is the table and rotate script I use in my initial setup.. Could be ready to merge.

### CODE REVIEW

**Comment by adubovikov** [comment]
yes, but lets make it with datetime stamp i.e.

isup_sipcapture_20160203, because I expect a lot traffic to this table and better split it before.

**Comment by zecke** [comment]
Ah sure. I understand partitioning based on the timestamp in theory but I have two gaps in my mental picture.
- How does inserting work from kamalio? Does it need to use "isup_capture" or pick one based on the _current_ time?
- How do we go from "isup_capture_YYYYMMDD" to YYYYMMDD+1. Will mysql create/rotate that automatically?

I am happy if you could point me to some docs.

**Comment by adubovikov** [comment]
1. we can go 3 ways: 
    a) parse the JSON object to a SQL string base on the table's schema in kamailio.cfg and use sqlops to insert the string into DB
    b) pass the JSON object to isup_capture/json_capture function of sipcapture module convert it into binary, extract fields and insert it into tables.
    c) call an internal API function of ss7ops from sipcapture module and use binary JSON object (not serialized) extract fields and insert into DB.
2. we have rotation script: https://github.com/sipcapture/homer-api/blob/master/scripts/homer_mysql_rotate.pl

and config file:
https://github.com/sipcapture/homer-api/blob/master/scripts/rotation.ini

**Comment by zecke** [comment]
I think this is obsolete/irrelevant for a long time.

**Pull request closed without merging**
