### PR TITLE
Debug error on parsing isup content

### PR DESCRIPTION
**Pull request by jso94**
Debug error on parsing isup content and add simple isup decoding using tshark

### CODE REVIEW

**Comment by lmangani** [comment]
Thanks @jso94 for the PR
Could you kindly sign our Contributor License Agreement? http://cla.qxip.net/

**Comment by lmangani** [comment]
Thanks for signing the CLA :) 

Could you contact us at support@sipcapture.org to discuss the PR?
We have some concerns with the tshark dependency and we can look into alternatives together.

**Comment by sergey-vb** [comment]
Hi All.

Thank you for parser for ISUP.
I have tested it and found few mistakes or it's only for my case...
1. String 
   `Content-Type: multipart/mixed;boundary="2123894789_1257887457"`
   have " character 0x22, but when it is used as a separator for multipart message it used without " character
   `--2123894789_1257887457 Content-Type: application/sdp`
   So I have changed your function to
   `private function getBoundaryName($content_type){
        preg_match('/boundary\=(.*)/',$content_type,$matches);
        return trim($matches[1],"\x00,\x09,\x0A,\x0B,\x0D,\x20,\x22");
   }`
2. When you make analyze if INVITE have ISUP and SDP you using 
   `preg_match('/boundary\=(.*)/',$data->content_type,$matches);
   //$boundary = $matches[1];`
   but since you have function getBoundaryName you can use it like
   `$boundary = $this->getBoundaryName($data->content_type);`
3. On RHEL/CentOS I have another path to wireshark, i thin better make it as a variable.

Please find atteched file Search.php which is working for me.

Thank you very match for you work!
WBR,
Sergey.
[Search.txt](https://github.com/sipcapture/homer-api/files/353700/Search.txt)
Please rename it to php as upload of php files does not supported.

**Comment by jso94** [comment]
Hi,
your are rigth.

I change that, and add another decode information.
And i use api/configutation.php to défine tshark use and path.

I'll send you the new file PM.

Jérôme.

2016-07-08 9:35 GMT+02:00 sergey-vb notifications@github.com:

**Comment by sergey-vb** [comment]
Thanks @jso94 now it works for me.

WBR,
Sergey.

**Comment by adubovikov** [comment]
Thank you. For me this is patch is temporally workaround. We have to work on own ISUP parser. Volunteers are welcome!

**Pull request merged**
