### PR TITLE
Initialize $boards variable to squelch PHP notice

### PR DESCRIPTION
**Pull request by mslehto**
Just copied same array() initialization as in [postIdDashboard()](https://github.com/sipcapture/homer-api/blob/master/api/RestApi/Dashboard.php#L304)

### CODE REVIEW

**Comment by adubovikov** [comment]
Hi Mikko, 

thank you for your pull request. Can you please sign CLA and we will apply the patch immediately ?

thank you again!

Wbr,
Alexandr

**Comment by mslehto** [comment]
Hi Alexandr!

I believe that paperwork is already done, see [pull request #41](https://github.com/sipcapture/homer-api/pull/41)

**Comment by lmangani** [comment]
Hi @mslehto sorry about this we switched to a new CLA which is now persistent. 
Thanks for your patience and PR!

**Comment by mslehto** [comment]
sure, let me know if you anything

**Comment by adubovikov** [comment]
@mslehto please click on the button or on this link:

https://cla-assistant.io/sipcapture/homer-api?pullRequest=131

thank you!

**Comment by mslehto** [comment]
hi, still something missing? have a nice.

**Pull request merged**
