### PR TITLE
refactored homer partition rotation script

### PR DESCRIPTION
**Pull request by kamunas**
I've made several bugfixes and code style adjustments.

strict mode is enabled in order to avoid scope issues.

### CODE REVIEW

**Comment by adubovikov** [comment]
Hello,
thank you for make it more professional :-) so far all good, but unfortunately you have removed MSG_SIZE procedure that definitely should be there. Is any reason for this ?

**Comment by kamunas** [comment]
You are right!, I missed that placeholder.  Fixed

**Comment by kamunas** [comment]
fixed

**Comment by adubovikov** [comment]
Thank you!

**Pull request merged**
